cd hadoop
wget http://apache.bytenet.in/hadoop/common/hadoop-2.6.0/hadoop-2.6.0.tar.gz
mv hadoop-2.6.0.tar.gz hadoop.tar.gz
cd ..
cd hbase
wget http://apache.bytenet.in/hbase/stable/hbase-0.98.9-hadoop2-bin.tar.gz
cd ..
cd flume
#Flume binary 
wget https://drive.google.com/file/d/0B8CZ9QLchKY9VE5MQnFwN0RQdXc/view?usp=sharing
cd ..
cd mongodb
wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.6.7.tgz
mv mongodb-linux-x86_64-2.6.7.tgz mongodb-linux-x86_64-2.6.7.tar.gz
cd ..
cd sqoop
wget http://apache.bytenet.in/sqoop/1.4.5/sqoop-1.4.5.bin__hadoop-2.0.4-alpha.tar.gz
cd ..
cd hive
wget http://apache.bytenet.in/hive/stable/apache-hive-1.0.0-bin.tar.gz
wget http://cdn.mysql.com/Downloads/Connector-J/mysql-connector-java-5.1.34.tar.gz
cd ..
cd mongo-hadoop
wget https://github.com/mongodb/mongo-hadoop/releases/download/r1.3.2/flume-1.3.2.jar
wget https://github.com/mongodb/mongo-hadoop/releases/download/r1.3.2/mongo-hadoop-core-1.3.2.jar
wget https://github.com/mongodb/mongo-hadoop/releases/download/r1.3.2/mongo-hadoop-hive-1.3.2.jar
wget https://github.com/mongodb/mongo-hadoop/releases/download/r1.3.2/mongo-hadoop-streaming-1.3.2.jar
wget http://central.maven.org/maven2/org/mongodb/mongo-java-driver/2.9.3/mongo-java-driver-2.9.3.jar
cd ..